<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('categories')->insert([
            [
                'code' => 'CPU-I5-13400F',
                'name' => 'Vi xử lý Intel Core i5-13400F',
                'category_type' => 'CPU',
                'specifications' => '10 nhân 16 luồng, Up to 4.6GHz, 20MB Cache, LGA 1700',
                'brand' => 'Intel',
                'image' => 'i5_13400f.jpg',
                'price' => 4890000.00,
                'stock' => 25,
                'warranty_months' => 36,
                'description' => 'Bộ vi xử lý tầm trung hiệu năng cao cho PC chơi game và đồ họa.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'RAM-KST-16G-D4',
                'name' => 'RAM Kingston Fury Beast 16GB DDR4 3200MHz',
                'category_type' => 'RAM',
                'specifications' => '16GB (1x16GB) DDR4, Bus 3200MHz, CL16, Tản nhiệt nhôm',
                'brand' => 'Kingston',
                'image' => 'ram_kingston_16gb.jpg',
                'price' => 950000.00,
                'stock' => 50,
                'warranty_months' => 36,
                'description' => 'Tản nhiệt nhôm đen mỏng nhẹ, tối ưu hiệu năng đa nhiệm.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'MB-ASUS-B760M',
                'name' => 'Bo mạch chủ Asus TUF GAMING B760M-PLUS WIFI',
                'category_type' => 'Mainboard',
                'specifications' => 'Micro-ATX, Socket LGA 1700, 4x DDR5, PCIe 5.0, Wi-Fi 6',
                'brand' => 'Asus',
                'image' => 'asus_b760m.jpg',
                'price' => 4150000.00,
                'stock' => 15,
                'warranty_months' => 36,
                'description' => 'Bo mạch chủ siêu bền chuẩn quân đội, tích hợp Wifi 6 tốc độ cao.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'VGA-MSI-RTX4060',
                'name' => 'Card màn hình MSI GeForce RTX 4060 VENTUS 2X 8G OC',
                'category_type' => 'VGA',
                'specifications' => '8GB GDDR6, 128-bit, PCIe 4.0, 3x DisplayPort, 1x HDMI',
                'brand' => 'MSI',
                'image' => 'msi_rtx4060.jpg',
                'price' => 7990000.00,
                'stock' => 10,
                'warranty_months' => 36,
                'description' => 'Kiến trúc Ada Lovelace hỗ trợ DLSS 3 và Ray Tracing chân thực.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'SSD-SAMSUNG-980-1T',
                'name' => 'Ổ cứng SSD Samsung 980 NVMe M.2 2280 1TB',
                'category_type' => 'SSD',
                'specifications' => '1TB M.2 NVMe PCIe Gen 3.0 x4, Đọc 3500MB/s, Ghi 3000MB/s',
                'brand' => 'Samsung',
                'image' => 'ssd_samsung_980.jpg',
                'price' => 2190000.00,
                'stock' => 40,
                'warranty_months' => 60,
                'description' => 'Tốc độ truy xuất dữ liệu cực nhanh, bảo hành chính hãng 5 năm.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'PSU-CORSAIR-CV650',
                'name' => 'Nguồn máy tính Corsair CV650 - 650W',
                'category_type' => 'Nguồn (PSU)',
                'specifications' => '650W, 80 Plus Bronze, Quạt 120mm, Dây cáp đen phẳng',
                'brand' => 'Corsair',
                'image' => 'corsair_cv650.jpg',
                'price' => 1350000.00,
                'stock' => 30,
                'warranty_months' => 36,
                'description' => 'Đạt chứng nhận 80 Plus Bronze cung cấp nguồn điện ổn định và êm ái.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'code' => 'IC-ATMEGA328P',
                'name' => 'Vi điều khiển ATmega328P-PU DIP-28',
                'category_type' => 'Linh kiện IC',
                'specifications' => '8-bit AVR, 32KB Flash, 16MHz, Điện áp 1.8V - 5.5V',
                'brand' => 'Microchip',
                'image' => 'atmega328p.jpg',
                'price' => 45000.00,
                'stock' => 200,
                'warranty_months' => 6,
                'description' => 'Con chip chuẩn được sử dụng phổ biến trong các bo mạch Arduino Uno R3.',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}